### ISSUE TITLE
MIDI note based on exit code?

### ISSUE THREAD

**Issue by mxmilkiib** [OpenMusicKontrollers/shells_bells.lv2#1]
Possible option for sending out a MIDI node that depends on the exit code of applications run in the shell?

**Comment by ventosus** [comment]
Hehe, sounds like fun.

I don't see a straightworward way to do so, but we'll figure out something for sure.

**Comment by ventosus** [comment]
As this is a just-for-fun plugin, this feature is out-of-scope.
